server:
  port: 8081

spring:
  application:
    name: item-service

  data:
    mongodb:
      uri: mongodb://localhost:27018/itemdb
      auto-index-creation: true

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

# Expose Swagger UI at /swagger-ui.html
springdoc:
  swagger-ui:
    path: /swagger-ui.html